version: "3"
services:
  nhaphang_admin:
    image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/www_admin
      - APACHE_RUN_DIR=/var/www/html/www_admin
      - APACHE_LOG_DIR=/var/log/apache2
    volumes:
      - ${NHAPHANG_SOURCE}:/var/www/html
    ports:
      - ${NHAPHANG_ADMIN_PORT}:80
    restart: unless-stopped
  nhaphang_order:
    image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/www_html
    volumes:
      - ${NHAPHANG_SOURCE}:/var/www/html
    ports:
      - ${NHAPHANG_ORDER_PORT}:80
    restart: unless-stopped
  # nhaphang_logistics:
  #   image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
  #   environment:
  #     - APACHE_DOCUMENT_ROOT=/var/www/html/www_html
  #   volumes:
  #     - ${NHAPHANG_LOGSITICS_SOURCE}:/var/www/html
  #   ports:
  #     - ${NHAPHANG_LOGSITICS_PORT}:80
  #   restart: unless-stopped
#  vitali:
#    image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
#    environment:
#      - APACHE_DOCUMENT_ROOT=/var/www/html/www_html
#    volumes:
#      - ${VITALI_SOURCE}:/var/www/html
#    ports:
#      - ${VITALI_PORT}:80
#    restart: unless-stopped
#  nhaphang_in:
#    image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
#    environment:
#      - APACHE_DOCUMENT_ROOT=/var/www/html/www_html
#    volumes:
#      - ${NHAPHANG_IN_SOURCE}:/var/www/html
#    ports:
#      - ${NHAPHANG_IN_PORT}:80
#    restart: unless-stopped
  baogam_admin:
    image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/www_admin
    volumes:
      - ${BAOGAM_SOURCE}:/var/www/html
    ports:
      - ${BAOGAM_ADMIN_PORT}:80
    restart: unless-stopped
  baogam_order:
    image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/www_html
    volumes:
      - ${BAOGAM_SOURCE}:/var/www/html
    ports:
      - ${BAOGAM_ORDER_PORT}:80
    restart: unless-stopped
  # baogam_logistics:
  #   image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
  #   environment:
  #     - APACHE_DOCUMENT_ROOT=/var/www/html/www_html
  #   volumes:
  #     - ${BAOGAM_LOGSITICS_SOURCE}:/var/www/html
  #   ports:
  #     - ${BAOGAM_LOGSITICS_PORT}:80
  #   restart: unless-stopped
#  vibaga:
#    image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
#    environment:
#      - APACHE_DOCUMENT_ROOT=/var/www/html/www_html
#    volumes:
#      - ${VIBAGA_SOURCE}:/var/www/html
#    ports:
#      - ${VIBAGA_PORT}:80
#    restart: unless-stopped
#  baogam_in:
#    image: ghcr.io/gobiz-vinasat/ali-docker:dev-apache
#    environment:
#      - APACHE_DOCUMENT_ROOT=/var/www/html/www_html
#    volumes:
#      - ${BAOGAM_IN_SOURCE}:/var/www/html
#    ports:
#      - ${BAOGAM_IN_PORT}:80
#    restart: unless-stopped
  mariadb:
    image: mariadb:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306
    restart: unless-stopped
  mongo:
    image: mongo:3.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123123
    volumes:
      - mongo:/data/db
    ports:
      - ${MONGO_PORT}:27017
    restart: unless-stopped
  redis:
    image: redis:3.2
    ports:
      - ${REDIS_PORT}:6379
    restart: unless-stopped
  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    restart: unless-stopped
volumes:
  mariadb:
  mongo:
